### PR TITLE
Prod

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by Thovi98** [comment]
I’ve just installed Audiobookshelf from this branch and : 

- After install, I had 502 bad gateway like on the CI, but after a little time (without doing anyting), it worked great.
- I tested with the Android app and it works great (anonymous user is granted at installation) https://github.com/YunoHost-Apps/audiobookshelf_ynh/issues/2

**Comment by Thovi98** [comment]
I’ve just installed Audiobookshelf from this branch and : 

- After install, I had 502 bad gateway like on the CI, but after a little time (without doing anyting), it worked great.
- I tested with the Android app and it works great (anonymous user is granted at installation) https://github.com/YunoHost-Apps/audiobookshelf_ynh/issues/2

**Comment by navanchauhan** [comment]
Let's try adding a sleep for 60 seconds to the install process

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
Looks like an issue with the node env

**Comment by navanchauhan** [comment]
!testme

**Pull request merged**
